label_mapping_1 = {
    "title": {"font_size": "\\zettaHuge", "style": ""},
    "first-level title": {"font_size": "\\exaHuge", "style": ""},
    "chapter-title": {"font_size": "\\petaHuge", "style": ""},
    "second-level title": {"font_size": "\\teraHuge", "style": ""},
    "headline": {"font_size": "\\kappaa", "style": ""},
    "section-title": {"font_size": "\\megaHuge", "style": ""},
    "third-level title": {"font_size": "\\superHuge", "style": ""},
    "sub-headline": {"font_size": "\\superHuge", "style": ""},
    "sub-section-title": {"font_size": "\\superHuge", "style": ""},
    "fourth-level title": {"font_size": "\\superHuge", "style": ""},
    "subsub-headline": {"font_size": "\\superHuge", "style": ""},
    "subsub-section-title": {"font_size": "\\superHuge", "style": ""},
    "fifth-level title": {"font_size": "\\superHuge", "style": ""},
    "paragraph": {"font_size": "\\kappaa", "style": ""},
    "quote": {"font_size": "\\kappaa", "style": ""},
    "lead": {"font_size": "\\kappaa", "style": ""},
    "section": {"font_size": "\\kappaa", "style": ""},
    "first-level-question": {"font_size": "\\kappaa", "style": ""},
    "second-level-question": {"font_size": "\\kappaa", "style": ""},
    "other question number": {"font_size": "\\kappaa", "style": ""},
    "third-level question number": {"font_size": "\\kappaa", "style": ""},
    "answer": {"font_size": "\\kappaa", "style": ""},
    "options": {"font_size": "\\kappaa", "style": ""},
    "ordered-list": {"font_size": "\\kappaa", "style": ""},
    "unordered-list": {"font_size": "\\kappaa", "style": ""},
    "sub-ordered-list": {"font_size": "\\kappaa", "style": ""},
    "figure-caption": {"font_size": "\\kappaa", "style": ""},
    "table-caption": {"font_size": "\\kappaa", "style": ""},
    "caption": {"font_size": "\\kappaa", "style": ""},
    "byline": {"font_size": "\\iotaa", "style": ""},
    "author": {"font_size": "\\kappaa", "style": ""},
    "dateline": {"font_size": "\\kappaa", "style": ""},
    "credit": {"font_size": "\\kappaa", "style": ""},
    "header": {"font_size": "\\pia", "style": ""},
    "footer": {"font_size": "\\nua", "style": ""},
    "page-number": {"font_size": "\\kappaa", "style": ""},
    "folio": {"font_size": "\\kappaa", "style": ""},
    "sidebar": {"font_size": "\\kappaa", "style": ""},
    "breakout": {"font_size": "\\rhoa", "style": ""},
    "kicker": {"font_size": "\\sigmaa", "style": ""},
    "jumpline": {"font_size": "\\kappaa", "style": ""},
    "footnote": {"font_size": "\\kappaa", "style": ""},
    "endnote": {"font_size": "\\kappaa", "style": ""},
    "reference": {"font_size": "\\kappaa", "style": ""},
    "marginal note": {"font_size": "\\kappaa", "style": ""},
    "code": {"font_size": "\\kappaa", "style": ""},
    "formula": {"font_size": "\\kappaa", "style": ""},
    "algorithm": {"font_size": "\\kappaa", "style": ""},
    "translator": {"font_size": "\\kappaa", "style": ""},
    "contact-info": {"font_size": "\\kappaa", "style": ""},
    "institute": {"font_size": "\\kappaa", "style": ""},
    "table note": {"font_size": "\\kappaa", "style": ""},
    "supplementary note": {"font_size": "\\kappaa", "style": ""},
    "_background_": {"font_size": "\\kappaa", "style": ""},
    "blank": {"font_size": "\\kappaa", "style": ""},
    "bracket": {"font_size": "\\kappaa", "style": ""},
    "underscore": {"font_size": "\\kappaa", "style": ""},
    "advertisement": {"font_size": "\\kappaa", "style": ""},
    "barcode": {"font_size": "\\kappaa", "style": ""},
    "bill": {"font_size": "\\kappaa", "style": ""},
    "catalogue": {"font_size": "\\kappaa", "style": ""},
    "correction": {"font_size": "\\kappaa", "style": ""},
    "drop cap": {"font_size": "\\kappaa", "style": ""},
    "editor's note": {"font_size": "\\kappaa", "style": ""},
    "examinee information": {"font_size": "\\kappaa", "style": ""},
    "figure": {"font_size": "\\kappaa", "style": ""},
    "flag": {"font_size": "\\kappaa", "style": ""},
    "index": {"font_size": "\\kappaa", "style": ""},
    "inside": {"font_size": "\\kappaa", "style": ""},
    "matching": {"font_size": "\\kappaa", "style": ""},
    "mugshot": {"font_size": "\\kappaa", "style": ""},
    "part": {"font_size": "\\kappaa", "style": ""},
    "play": {"font_size": "\\kappaa", "style": ""},
    "poem": {"font_size": "\\kappaa", "style": ""},
    "QR code": {"font_size": "\\kappaa", "style": ""},
    "sealing line": {"font_size": "\\kappaa", "style": ""},
    "table": {"font_size": "\\kappaa", "style": ""},
    "teasers": {"font_size": "\\kappaa", "style": ""},
    "weather forecast": {"font_size": "\\kappaa", "style": ""},
}

label_mapping_2 = {
    "title": {"font_size": "\\megaHuge", "style": ""},
    "first-level title": {"font_size": "\\superHuge", "style": ""},
    "chapter-title": {"font_size": "\\veryHuge", "style": ""},
    "second-level title": {"font_size": "\\alphaa", "style": ""},
    "headline": {"font_size": "\\kappaa", "style": ""},
    "section-title": {"font_size": "\\gammaa", "style": ""},
    "third-level title": {"font_size": "\\deltaa", "style": ""},
    "sub-headline": {"font_size": "\\deltaa", "style": ""},
    "sub-section-title": {"font_size": "\\deltaa", "style": ""},
    "fourth-level title": {"font_size": "\\epsilona", "style": ""},
    "subsub-headline": {"font_size": "\\epsilona", "style": ""},
    "subsub-section-title": {"font_size": "\\epsilona", "style": ""},
    "fifth-level title": {"font_size": "\\veryHuge", "style": ""},
    "paragraph": {"font_size": "\\mua", "style": ""},
    "quote": {"font_size": "\\mua", "style": ""},
    "lead": {"font_size": "\\mua", "style": ""},
    "section": {"font_size": "\\mua", "style": ""},
    "first-level-question": {"font_size": "\\mua", "style": ""},
    "second-level-question": {"font_size": "\\mua", "style": ""},
    "other question number": {"font_size": "\\mua", "style": ""},
    "third-level question number": {"font_size": "\\mua", "style": ""},
    "answer": {"font_size": "\\mua", "style": ""},
    "options": {"font_size": "\\mua", "style": ""},
    "ordered-list": {"font_size": "\\mua", "style": ""},
    "unordered-list": {"font_size": "\\mua", "style": ""},
    "sub-ordered-list": {"font_size": "\\mua", "style": ""},
    "figure-caption": {"font_size": "\\mua", "style": ""},
    "table-caption": {"font_size": "\\mua", "style": ""},
    "caption": {"font_size": "\\mua", "style": ""},
    "byline": {"font_size": "\\iotaa", "style": ""},
    "author": {"font_size": "\\mua", "style": ""},
    "dateline": {"font_size": "\\veryHuge", "style": ""},
    "credit": {"font_size": "\\mua", "style": ""},
    "header": {"font_size": "\\pia", "style": ""},
    "footer": {"font_size": "\\nua", "style": ""},
    "page-number": {"font_size": "\\mua", "style": ""},
    "folio": {"font_size": "\\mua", "style": ""},
    "sidebar": {"font_size": "\\mua", "style": ""},
    "breakout": {"font_size": "\\rhoa", "style": ""},
    "kicker": {"font_size": "\\sigmaa", "style": ""},
    "jumpline": {"font_size": "\\mua", "style": ""},
    "footnote": {"font_size": "\\mua", "style": ""},
    "endnote": {"font_size": "\\mua", "style": ""},
    "reference": {"font_size": "\\mua", "style": ""},
    "marginal note": {"font_size": "\\mua", "style": ""},
    "code": {"font_size": "\\mua", "style": ""},
    "formula": {"font_size": "\\mua", "style": ""},
    "algorithm": {"font_size": "\\mua", "style": ""},
    "translator": {"font_size": "\\mua", "style": ""},
    "contact-info": {"font_size": "\\mua", "style": ""},
    "institute": {"font_size": "\\mua", "style": ""},
    "table note": {"font_size": "\\mua", "style": ""},
    "supplementary note": {"font_size": "\\mua", "style": ""},
    "_background_": {"font_size": "\\mua", "style": ""},
    "blank": {"font_size": "\\mua", "style": ""},
    "bracket": {"font_size": "\\mua", "style": ""},
    "underscore": {"font_size": "\\mua", "style": ""},
    "advertisement": {"font_size": "\\mua", "style": ""},
    "barcode": {"font_size": "\\mua", "style": ""},
    "bill": {"font_size": "\\mua", "style": ""},
    "catalogue": {"font_size": "\\mua", "style": ""},
    "correction": {"font_size": "\\mua", "style": ""},
    "drop cap": {"font_size": "\\mua", "style": ""},
    "editor's note": {"font_size": "\\mua", "style": ""},
    "examinee information": {"font_size": "\\mua", "style": ""},
    "figure": {"font_size": "\\mua", "style": ""},
    "flag": {"font_size": "\\mua", "style": ""},
    "index": {"font_size": "\\mua", "style": ""},
    "inside": {"font_size": "\\mua", "style": ""},
    "matching": {"font_size": "\\mua", "style": ""},
    "mugshot": {"font_size": "\\mua", "style": ""},
    "part": {"font_size": "\\mua", "style": ""},
    "play": {"font_size": "\\mua", "style": ""},
    "poem": {"font_size": "\\mua", "style": ""},
    "QR code": {"font_size": "\\mua", "style": ""},
    "sealing line": {"font_size": "\\mua", "style": ""},
    "table": {"font_size": "\\mua", "style": ""},
    "teasers": {"font_size": "\\mua", "style": ""},
    "weather forecast": {"font_size": "\\mua", "style": ""},
}

label_mapping_3 = {
    "title": {"font_size": "\\gammaa", "style": ""},
    "first-level title": {"font_size": "\\deltaa", "style": ""},
    "chapter-title": {"font_size": "\\epsilona", "style": ""},
    "second-level title": {"font_size": "\\veryHuge", "style": ""},
    "headline": {"font_size": "\\zetaa", "style": ""},
    "section-title": {"font_size": "\\kappaa", "style": ""},
    "third-level title": {"font_size": "\\veryLarge", "style": ""},
    "sub-headline": {"font_size": "\\veryLarge", "style": ""},
    "sub-section-title": {"font_size": "\\veryLarge", "style": ""},
    "fourth-level title": {"font_size": "\\iotaa", "style": ""},
    "subsub-headline": {"font_size": "\\iotaa", "style": ""},
    "subsub-section-title": {"font_size": "\\iotaa", "style": ""},
    "fifth-level title": {"font_size": "\\pia", "style": ""},
    "paragraph": {"font_size": "\\pia", "style": ""},
    "quote": {"font_size": "\\pia", "style": ""},
    "lead": {"font_size": "\\pia", "style": ""},
    "section": {"font_size": "\\pia", "style": ""},
    "first-level-question": {"font_size": "\\pia", "style": ""},
    "second-level-question": {"font_size": "\\pia", "style": ""},
    "other question number": {"font_size": "\\pia", "style": ""},
    "third-level question number": {"font_size": "\\pia", "style": ""},
    "answer": {"font_size": "\\pia", "style": ""},
    "options": {"font_size": "\\pia", "style": ""},
    "ordered-list": {"font_size": "\\pia", "style": ""},
    "unordered-list": {"font_size": "\\pia", "style": ""},
    "sub-ordered-list": {"font_size": "\\pia", "style": ""},
    "figure-caption": {"font_size": "\\pia", "style": ""},
    "table-caption": {"font_size": "\\pia", "style": ""},
    "caption": {"font_size": "\\pia", "style": ""},
    "byline": {"font_size": "\\iotaa", "style": ""},
    "author": {"font_size": "\\pia", "style": ""},
    "dateline": {"font_size": "\\veryHuge", "style": ""},
    "credit": {"font_size": "\\pia", "style": ""},
    "header": {"font_size": "\\pia", "style": ""},
    "footer": {"font_size": "\\nua", "style": ""},
    "page-number": {"font_size": "\\pia", "style": ""},
    "folio": {"font_size": "\\pia", "style": ""},
    "sidebar": {"font_size": "\\pia", "style": ""},
    "breakout": {"font_size": "\\rhoa", "style": ""},
    "kicker": {"font_size": "\\sigmaa", "style": ""},
    "jumpline": {"font_size": "\\pia", "style": ""},
    "footnote": {"font_size": "\\pia", "style": ""},
    "endnote": {"font_size": "\\pia", "style": ""},
    "reference": {"font_size": "\\pia", "style": ""},
    "marginal note": {"font_size": "\\pia", "style": ""},
    "code": {"font_size": "\\pia", "style": ""},
    "formula": {"font_size": "\\pia", "style": ""},
    "algorithm": {"font_size": "\\pia", "style": ""},
    "translator": {"font_size": "\\pia", "style": ""},
    "contact-info": {"font_size": "\\pia", "style": ""},
    "institute": {"font_size": "\\pia", "style": ""},
    "table note": {"font_size": "\\pia", "style": ""},
    "supplementary note": {"font_size": "\\pia", "style": ""},
    "_background_": {"font_size": "\\pia", "style": ""},
    "blank": {"font_size": "\\pia", "style": ""},
    "bracket": {"font_size": "\\pia", "style": ""},
    "underscore": {"font_size": "\\pia", "style": ""},
    "advertisement": {"font_size": "\\pia", "style": ""},
    "barcode": {"font_size": "\\pia", "style": ""},
    "bill": {"font_size": "\\pia", "style": ""},
    "catalogue": {"font_size": "\\pia", "style": ""},
    "correction": {"font_size": "\\pia", "style": ""},
    "drop cap": {"font_size": "\\pia", "style": ""},
    "editor's note": {"font_size": "\\pia", "style": ""},
    "examinee information": {"font_size": "\\pia", "style": ""},
    "figure": {"font_size": "\\pia", "style": ""},
    "flag": {"font_size": "\\pia", "style": ""},
    "index": {"font_size": "\\pia", "style": ""},
    "inside": {"font_size": "\\pia", "style": ""},
    "matching": {"font_size": "\\pia", "style": ""},
    "mugshot": {"font_size": "\\pia", "style": ""},
    "part": {"font_size": "\\pia", "style": ""},
    "play": {"font_size": "\\pia", "style": ""},
    "poem": {"font_size": "\\pia", "style": ""},
    "QR code": {"font_size": "\\pia", "style": ""},
    "sealing line": {"font_size": "\\pia", "style": ""},
    "table": {"font_size": "\\pia", "style": ""},
    "teasers": {"font_size": "\\pia", "style": ""},
    "weather forecast": {"font_size": "\\pia", "style": ""},
}


label_mapping_4 = {
    "title": {"font_size": "\\kappaa", "style": ""},
    "first-level title": {"font_size": "\\veryLarge", "style": ""},
    "chapter-title": {"font_size": "\\iotaa", "style": ""},
    "second-level title": {"font_size": "\\mua", "style": ""},
    "headline": {"font_size": "\\verylarge", "style": ""},
    "section-title": {"font_size": "\\lambdaa", "style": ""},
    "third-level title": {"font_size": "\\pia", "style": ""},
    "sub-headline": {"font_size": "\\pia", "style": ""},
    "sub-section-title": {"font_size": "\\pia", "style": ""},
    "fourth-level title": {"font_size": "\\nua", "style": ""},
    "subsub-headline": {"font_size": "\\nua", "style": ""},
    "subsub-section-title": {"font_size": "\\nua", "style": ""},
    "fifth-level title": {"font_size": "\\pia", "style": ""},
    "paragraph": {"font_size": "\\pia", "style": ""},
    "quote": {"font_size": "\\pia", "style": ""},
    "lead": {"font_size": "\\pia", "style": ""},
    "section": {"font_size": "\\pia", "style": ""},
    "first-level-question": {"font_size": "\\pia", "style": ""},
    "second-level-question": {"font_size": "\\pia", "style": ""},
    "other question number": {"font_size": "\\pia", "style": ""},
    "third-level question number": {"font_size": "\\pia", "style": ""},
    "answer": {"font_size": "\\pia", "style": ""},
    "options": {"font_size": "\\pia", "style": ""},
    "ordered-list": {"font_size": "\\pia", "style": ""},
    "unordered-list": {"font_size": "\\pia", "style": ""},
    "sub-ordered-list": {"font_size": "\\pia", "style": ""},
    "figure-caption": {"font_size": "\\pia", "style": ""},
    "table-caption": {"font_size": "\\pia", "style": ""},
    "caption": {"font_size": "\\pia", "style": ""},
    "byline": {"font_size": "\\iotaa", "style": ""},
    "author": {"font_size": "\\pia", "style": ""},
    "dateline": {"font_size": "\\veryHuge", "style": ""},
    "credit": {"font_size": "\\pia", "style": ""},
    "header": {"font_size": "\\pia", "style": ""},
    "footer": {"font_size": "\\nua", "style": ""},
    "page-number": {"font_size": "\\pia", "style": ""},
    "folio": {"font_size": "\\pia", "style": ""},
    "sidebar": {"font_size": "\\pia", "style": ""},
    "breakout": {"font_size": "\\rhoa", "style": ""},
    "kicker": {"font_size": "\\sigmaa", "style": ""},
    "jumpline": {"font_size": "\\pia", "style": ""},
    "footnote": {"font_size": "\\pia", "style": ""},
    "endnote": {"font_size": "\\pia", "style": ""},
    "reference": {"font_size": "\\pia", "style": ""},
    "marginal note": {"font_size": "\\pia", "style": ""},
    "code": {"font_size": "\\pia", "style": ""},
    "formula": {"font_size": "\\pia", "style": ""},
    "algorithm": {"font_size": "\\pia", "style": ""},
    "translator": {"font_size": "\\pia", "style": ""},
    "contact-info": {"font_size": "\\pia", "style": ""},
    "institute": {"font_size": "\\pia", "style": ""},
    "table note": {"font_size": "\\pia", "style": ""},
    "supplementary note": {"font_size": "\\pia", "style": ""},
    "_background_": {"font_size": "\\pia", "style": ""},
    "blank": {"font_size": "\\pia", "style": ""},
    "bracket": {"font_size": "\\pia", "style": ""},
    "underscore": {"font_size": "\\pia", "style": ""},
    "advertisement": {"font_size": "\\pia", "style": ""},
    "barcode": {"font_size": "\\pia", "style": ""},
    "bill": {"font_size": "\\pia", "style": ""},
    "catalogue": {"font_size": "\\pia", "style": ""},
    "correction": {"font_size": "\\pia", "style": ""},
    "drop cap": {"font_size": "\\pia", "style": ""},
    "editor's note": {"font_size": "\\pia", "style": ""},
    "examinee information": {"font_size": "\\pia", "style": ""},
    "figure": {"font_size": "\\pia", "style": ""},
    "flag": {"font_size": "\\pia", "style": ""},
    "index": {"font_size": "\\pia", "style": ""},
    "inside": {"font_size": "\\pia", "style": ""},
    "matching": {"font_size": "\\pia", "style": ""},
    "mugshot": {"font_size": "\\pia", "style": ""},
    "part": {"font_size": "\\pia", "style": ""},
    "play": {"font_size": "\\pia", "style": ""},
    "poem": {"font_size": "\\pia", "style": ""},
    "QR code": {"font_size": "\\pia", "style": ""},
    "sealing line": {"font_size": "\\pia", "style": ""},
    "table": {"font_size": "\\pia", "style": ""},
    "teasers": {"font_size": "\\pia", "style": ""},
    "weather forecast": {"font_size": "\\pia", "style": ""},
}


label_mapping_5 = {
    "title": {"font_size": "\\Huge", "style": ""},
    "first-level title": {"font_size": "\\Huge", "style": ""},
    "chapter-title": {"font_size": "\\Huge", "style": ""},
    "second-level title": {"font_size": "\\Huge", "style": ""},
    "headline": {"font_size": "\\huge", "style": ""},
    "section-title": {"font_size": "\\Huge", "style": ""},
    "third-level title": {"font_size": "\\huge", "style": ""},
    "sub-headline": {"font_size": "\\huge", "style": ""},
    "sub-section-title": {"font_size": "\\huge", "style": ""},
    "fourth-level title": {"font_size": "\\normalsize", "style": ""},
    "subsub-headline": {"font_size": "\\LARGE", "style": ""},
    "subsub-section-title": {"font_size": "\\large", "style": ""},
    "fifth-level title": {"font_size": "\\huge", "style": ""},
    "paragraph": {"font_size": "\\normalsize", "style": ""},
    "quote": {"font_size": "\\normalsize", "style": ""},
    "lead": {"font_size": "\\normalsize", "style": ""},
    "section": {"font_size": "\\normalsize", "style": ""},
    "first-level-question": {"font_size": "\\normalsize", "style": ""},
    "second-level-question": {"font_size": "\\normalsize", "style": ""},
    "other question number": {"font_size": "\\normalsize", "style": ""},
    "third-level question number": {"font_size": "\\normalsize", "style": ""},
    "answer": {"font_size": "\\normalsize", "style": ""},
    "options": {"font_size": "\\normalsize", "style": ""},
    "ordered-list": {"font_size": "\\normalsize", "style": ""},
    "unordered-list": {"font_size": "\\normalsize", "style": ""},
    "sub-ordered-list": {"font_size": "\\normalsize", "style": ""},
    "figure-caption": {"font_size": "\\normalsize", "style": ""},
    "table-caption": {"font_size": "\\normalsize", "style": ""},
    "caption": {"font_size": "\\normalsize", "style": ""},
    "byline": {"font_size": "\\iotaa", "style": ""},
    "author": {"font_size": "\\normalsize", "style": ""},
    "dateline": {"font_size": "\\veryHuge", "style": ""},
    "credit": {"font_size": "\\normalsize", "style": ""},
    "header": {"font_size": "\\normalsize", "style": ""},
    "footer": {"font_size": "\\nua", "style": ""},
    "page-number": {"font_size": "\\normalsize", "style": ""},
    "folio": {"font_size": "\\normalsize", "style": ""},
    "sidebar": {"font_size": "\\normalsize", "style": ""},
    "breakout": {"font_size": "\\rhoa", "style": ""},
    "kicker": {"font_size": "\\normalsize", "style": ""},
    "jumpline": {"font_size": "\\normalsize", "style": ""},
    "footnote": {"font_size": "\\normalsize", "style": ""},
    "endnote": {"font_size": "\\normalsize", "style": ""},
    "reference": {"font_size": "\\normalsize", "style": ""},
    "marginal note": {"font_size": "\\normalsize", "style": ""},
    "code": {"font_size": "\\normalsize", "style": ""},
    "formula": {"font_size": "\\normalsize", "style": ""},
    "algorithm": {"font_size": "\\normalsize", "style": ""},
    "translator": {"font_size": "\\normalsize", "style": ""},
    "contact-info": {"font_size": "\\normalsize", "style": ""},
    "institute": {"font_size": "\\normalsize", "style": ""},
    "table note": {"font_size": "\\normalsize", "style": ""},
    "supplementary note": {"font_size": "\\normalsize", "style": ""},
    "_background_": {"font_size": "\\normalsize", "style": ""},
    "blank": {"font_size": "\\normalsize", "style": ""},
    "bracket": {"font_size": "\\normalsize", "style": ""},
    "underscore": {"font_size": "\\normalsize", "style": ""},
    "advertisement": {"font_size": "\\normalsize", "style": ""},
    "barcode": {"font_size": "\\normalsize", "style": ""},
    "bill": {"font_size": "\\normalsize", "style": ""},
    "catalogue": {"font_size": "\\normalsize", "style": ""},
    "correction": {"font_size": "\\normalsize", "style": ""},
    "drop cap": {"font_size": "\\normalsize", "style": ""},
    "editor's note": {"font_size": "\\normalsize", "style": ""},
    "examinee information": {"font_size": "\\normalsize", "style": ""},
    "figure": {"font_size": "\\normalsize", "style": ""},
    "flag": {"font_size": "\\normalsize", "style": ""},
    "index": {"font_size": "\\normalsize", "style": ""},
    "inside": {"font_size": "\\normalsize", "style": ""},
    "matching": {"font_size": "\\normalsize", "style": ""},
    "mugshot": {"font_size": "\\normalsize", "style": ""},
    "part": {"font_size": "\\normalsize", "style": ""},
    "play": {"font_size": "\\normalsize", "style": ""},
    "poem": {"font_size": "\\normalsize", "style": ""},
    "QR code": {"font_size": "\\normalsize", "style": ""},
    "sealing line": {"font_size": "\\normalsize", "style": ""},
    "table": {"font_size": "\\normalsize", "style": ""},
    "teasers": {"font_size": "\\normalsize", "style": ""},
    "weather forecast": {"font_size": "\\normalsize", "style": ""},
}


label_mapping_default = {
    "title": {"font_size": "\\zettaHuge", "style": ""},
    "first-level title": {"font_size": "\\exaHuge", "style": ""},
    "chapter-title": {"font_size": "\\petaHuge", "style": ""},
    "second-level title": {"font_size": "\\teraHuge", "style": ""},
    "headline": {"font_size": "\\kappaa", "style": ""},
    "section-title": {"font_size": "\\megaHuge", "style": ""},
    "third-level title": {"font_size": "\\superHuge", "style": ""},
    "sub-headline": {"font_size": "\\superHuge", "style": ""},
    "sub-section-title": {"font_size": "\\superHuge", "style": ""},
    "fourth-level title": {"font_size": "\\kappaa", "style": ""},
    "subsub-headline": {"font_size": "\\gigaHuge", "style": ""},
    "subsub-section-title": {"font_size": "\\superHuge", "style": ""},
    "fifth-level title": {"font_size": "\\gigaHuge", "style": ""},
    "paragraph": {"font_size": "\\kappaa", "style": ""},
    "quote": {"font_size": "\\kappaa", "style": ""},
    "lead": {"font_size": "\\kappaa", "style": ""},
    "section": {"font_size": "\\kappaa", "style": ""},
    "first-level-question": {"font_size": "\\kappaa", "style": ""},
    "second-level-question": {"font_size": "\\kappaa", "style": ""},
    "other question number": {"font_size": "\\kappaa", "style": ""},
    "third-level question number": {"font_size": "\\kappaa", "style": ""},
    "answer": {"font_size": "\\kappaa", "style": ""},
    "options": {"font_size": "\\kappaa", "style": ""},
    "ordered-list": {"font_size": "\\kappaa", "style": ""},
    "unordered-list": {"font_size": "\\kappaa", "style": ""},
    "sub-ordered-list": {"font_size": "\\kappaa", "style": ""},
    "figure-caption": {"font_size": "\\kappaa", "style": ""},
    "table-caption": {"font_size": "\\kappaa", "style": ""},
    "caption": {"font_size": "\\kappaa", "style": ""},
    "byline": {"font_size": "\\iotaa", "style": ""},
    "author": {"font_size": "\\kappaa", "style": ""},
    "dateline": {"font_size": "\\kappaa", "style": ""},
    "credit": {"font_size": "\\kappaa", "style": ""},
    "header": {"font_size": "\\pia", "style": ""},
    "footer": {"font_size": "\\nua", "style": ""},
    "page-number": {"font_size": "\\kappaa", "style": ""},
    "folio": {"font_size": "\\kappaa", "style": ""},
    "sidebar": {"font_size": "\\kappaa", "style": ""},
    "breakout": {"font_size": "\\rhoa", "style": ""},
    "kicker": {"font_size": "\\sigmaa", "style": ""},
    "jumpline": {"font_size": "\\kappaa", "style": ""},
    "footnote": {"font_size": "\\kappaa", "style": ""},
    "endnote": {"font_size": "\\kappaa", "style": ""},
    "reference": {"font_size": "\\kappaa", "style": ""},
    "marginal note": {"font_size": "\\kappaa", "style": ""},
    "code": {"font_size": "\\kappaa", "style": ""},
    "formula": {"font_size": "\\kappaa", "style": ""},
    "algorithm": {"font_size": "\\kappaa", "style": ""},
    "translator": {"font_size": "\\kappaa", "style": ""},
    "contact-info": {"font_size": "\\kappaa", "style": ""},
    "institute": {"font_size": "\\kappaa", "style": ""},
    "table note": {"font_size": "\\kappaa", "style": ""},
    "supplementary note": {"font_size": "\\kappaa", "style": ""},
    "_background_": {"font_size": "\\kappaa", "style": ""},
    "blank": {"font_size": "\\kappaa", "style": ""},
    "bracket": {"font_size": "\\kappaa", "style": ""},
    "underscore": {"font_size": "\\kappaa", "style": ""},
    "advertisement": {"font_size": "\\kappaa", "style": ""},
    "barcode": {"font_size": "\\kappaa", "style": ""},
    "bill": {"font_size": "\\kappaa", "style": ""},
    "catalogue": {"font_size": "\\kappaa", "style": ""},
    "correction": {"font_size": "\\kappaa", "style": ""},
    "drop cap": {"font_size": "\\kappaa", "style": ""},
    "editor's note": {"font_size": "\\kappaa", "style": ""},
    "examinee information": {"font_size": "\\kappaa", "style": ""},
    "figure": {"font_size": "\\kappaa", "style": ""},
    "flag": {"font_size": "\\kappaa", "style": ""},
    "index": {"font_size": "\\kappaa", "style": ""},
    "inside": {"font_size": "\\kappaa", "style": ""},
    "matching": {"font_size": "\\kappaa", "style": ""},
    "mugshot": {"font_size": "\\kappaa", "style": ""},
    "part": {"font_size": "\\kappaa", "style": ""},
    "play": {"font_size": "\\kappaa", "style": ""},
    "poem": {"font_size": "\\kappaa", "style": ""},
    "QR code": {"font_size": "\\kappaa", "style": ""},
    "sealing line": {"font_size": "\\kappaa", "style": ""},
    "table": {"font_size": "\\kappaa", "style": ""},
    "teasers": {"font_size": "\\kappaa", "style": ""},
    "weather forecast": {"font_size": "\\kappaa", "style": ""},
}

